### PR TITLE
[JENKINS-74842] `ClassCastException` in `ReverseProxySecurityRealm#loadGroupByGroupname2`

### PR DESCRIPTION
**Pull request by basil**
Sprinkling `SetContextClassLoader` in yet another place hoping that this fixes [JENKINS-74842](https://issues.jenkins.io/browse/JENKINS-74842).

### Testing done

None

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Seems harmless, though I would expect any bug like this to be reproducible in tests, perhaps some extension to https://github.com/jenkinsci/reverse-proxy-auth-plugin/blob/d99619b655b119234315627536b332a875f71ad0/src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/docker/PlanetExpressTest.java#L103-L104 ?

**Comment by basil** [comment]
Thanks, Jesse! Out of curiosity, why was this plugin not adapted to Spring Security as part of the Acegi removal project?

**Comment by jglick** [comment]
> why was this plugin not adapted to Spring Security

A good question. At this point I do not really remember. It would have made sense to follow up #40 analogously to https://github.com/jenkinsci/ldap-plugin/pull/49.

**Comment by basil** [comment]
Just as it would have made sense to write a test for this bug. :man_shrugging:

**Comment by basil** [comment]
@sboardwell Could this please be released?

**Comment by sboardwell** [comment]
@basil I can do it this weekend. Travelling at the moment and the internet is not the best.

**Comment by jglick** [comment]
@sboardwell FYI if you set up https://www.jenkins.io/doc/developer/publishing/releasing-cd/ you can trigger a release from your phone (unless of course you need to do manual testing first).

**Comment by sboardwell** [comment]
I was going to do that as well at some point. How long does it take to set up approximately? I might do that and then release.

**Comment by jglick** [comment]
> How long does it take to set up approximately?

Generally not long. If you like, I could file a PR for this repo which you could review & approve. I think I have physical permissions to merge here, probably for historical reasons.

**Comment by sboardwell** [comment]
That would be great if you have the time.

**Comment by jglick** [comment]
@sboardwell OK please review https://github.com/jenkins-infra/repository-permissions-updater/pull/4177 + https://github.com/jenkinsci/reverse-proxy-auth-plugin/pull/154

**Comment by jglick** [comment]
Released as https://github.com/jenkinsci/reverse-proxy-auth-plugin/releases/tag/238.v82ceca_8417a_6

**Pull request merged**
