### PR TITLE
[JENKINS-22402] authContext and authorityUpdateCache should be transient too

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-22402](https://issues.jenkins-ci.org/browse/JENKINS-22402)

Follow-up to #15.

Untested—I have no idea offhand how to create a test environment for this. Just observed a situation in which the XStream-serialized form of `authContext` was over 200Mb, which is surely not right.

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@wilderrodrigues Would it be possible to get this fix released? Without it the plugin won't longer work on Jenkins 2.102+

See https://issues.jenkins-ci.org/browse/JENKINS-48970

**Comment by oleg-nenashev** [comment]
@wilderrodrigues I have created the ownership handover request here: https://groups.google.com/forum/#!topic/jenkinsci-dev/9mX-S7kLnHk. If you have no interest in maintaining this plugin anymore (or if you want to let us do the current release only), could you please respond to that thread so we could proceed with the release? Thanks for your attention in advance

CC @Wadeck

**Pull request merged**
