### PR TITLE
[JENKINS-74800] Reverse Proxy Auth plugin 1.7.7 fails with 2.479.1

### PR DESCRIPTION
**Pull request by basil**
### Testing done

`mvn clean verify`

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Following up #40.

**Comment by mpalourdio** [comment]
That's neat, we were spotted by he same bug and had began migrating to Spring 6, but had hard times with some methods that do not exist anymore (`LdapUserDetails#getAttributes`).Your implementation is much better, as I have no XP in jenkins plugin API

https://github.com/jenkinsci/reverse-proxy-auth-plugin/compare/master...mpalourdio:reverse-proxy-auth-plugin:spring6

**Comment by basil** [comment]
@mpalourdio Can you test the incremental build and let me know how it works? I don't actually use this plugin in production and have done only light testing. I haven't tested the header groups feature, so I would appreciate if someone could test that.

**Comment by mpalourdio** [comment]
AFAIK, the header groups feature has never landed in production, it's in master for a while, but never released. Will give this a shot early next week.

**Comment by sboardwell** [comment]
thanks @basil and @mpalourdio for the changes and testing here.

**Comment by basil** [comment]
@mpalourdio Thanks!

**Comment by basil** [comment]
@sboardwell Are you interested in performing a release? That would provide relief to any affected user(s).

**Comment by sboardwell** [comment]
@basil I could do it either tonight or tomorrow.

**Pull request merged**
