### PR TITLE
Add email and display name header injection support - revised from PR #30

### PR DESCRIPTION
**Pull request by akrasinsky**
This is a revised version from PR https://github.com/jenkinsci/reverse-proxy-auth-plugin/pull/30

Original text: 

> Reverse-proxy-auth-plugin supports name & groups header injections but emails and display name are fetched from the LDAP server.
>
> This fork add email and display name header injection support.
> Thus we can manage authentication and user profile data with an httpd server.
>
> What's more, using an httpd server as a reverse proxy, provides a simple solution to:
>
> - connect to several LDAP servers (even with different structures)
> - use technical users managed in the httpd server
> - create an SSO plateform with other integrated applications
> 
> The original fork was made on tag 1.4.

### CODE REVIEW

**Comment by akrasinsky** [comment]
@sboardwell Hi could you have a look at this?

**Comment by sboardwell** [comment]
> @sboardwell Hi could you have a look at this?

Sorry, missed this somehow. Will check in the next few days. Thanks :+1:

**Review by sboardwell — COMMENTED** [review]
Looks good. I've added a few nitpicks wrt code styling. Would you be able to add a test as well?

**Comment by akrasinsky** [comment]
Thank you, I'll have a look what I can test.

**Comment by akrasinsky** [comment]
I added some basic tests

**Comment by akrasinsky** [comment]
It would be great if you could resolve the issue.

**Pull request merged**
