### PR TITLE
Display name email address management

### PR DESCRIPTION
**Pull request by astik**
This PR adds email and name attributes to LDAP configuration.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Thanks for the contribution, @astik !

I will review / merge and create a release containing your changes.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Another question, @astik: do you have Jenkins running with those changes? 

Cheers,
Wilder

**Comment by astik** [comment]
Yes I do, we need it for my company.
@mabes is the one administrating our jenkins instance.

**Comment by tienju** [comment]
I installed the plugin with this PR included to a test Jenkins and it seems to work just fine. Hoping for a new plugin version release with this PR included, so that I can update our production masters more easily. :)

**Pull request merged**
